/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */
declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }

  interface HTMLAttributes {}
}


import {
  App as BmiApp
} from './components/app/app.component';

declare global {
  interface HTMLBmiAppElement extends BmiApp, HTMLStencilElement {
  }
  var HTMLBmiAppElement: {
    prototype: HTMLBmiAppElement;
    new (): HTMLBmiAppElement;
  };
  interface HTMLElementTagNameMap {
    "bmi-app": HTMLBmiAppElement;
  }
  interface ElementTagNameMap {
    "bmi-app": HTMLBmiAppElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "bmi-app": JSXElements.BmiAppAttributes;
    }
  }
  namespace JSXElements {
    export interface BmiAppAttributes extends HTMLAttributes {
      
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
